[workspace]
members = ["client", "server", "common"]
resolver = "2"

[workspace.dependencies]
bevy = "0.10.1"
bevy_renet = "0.0.7"

[profile.dev]
opt-level = 3

[profile.release]
lto = "thin"

[patch.crates-io]
ilattice = { git = "https://github.com/Game4all/ilattice-rs", branch = "update-glam" }
